server:
  port: 8081
spring:
  application:
    name: user-service-homework
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:${user.home}/.h2/${spring.application.name}/userService
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.format-sql: true
    show-sql: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    schemas:
      - PUBLIC
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    loadbalancer:
      ribbon:
        enable: false
basic:
  auth:
    github:
      token-uri: https://api.github.com
      username: ABC
      password: 123456
